### ISSUE TITLE
no such file or directory: /opt/homebrew/bin/brew

### ISSUE THREAD

**Issue by ajmoorexyz** [brandon-fryslie/rad-plugins#3]
[Line no.](https://github.com/brandon-fryslie/rad-plugins/blob/master/homebrew/homebrew.plugin.zsh#L16)

```
/Users/first.last/.zgen/brandon-fryslie/rad-plugins-master/homebrew/homebrew.plugin.zsh:16: no such file or directory: /opt/homebrew/bin/brew
```

I have...
```
❯ which brew
/usr/local/bin/brew
```
which is linked like so
```
brew -> /usr/local/Homebrew/bin/brew
```

```
❯ brew --version
Homebrew 3.3.3
Homebrew/homebrew-core (git revision aba84991637; last commit 2021-11-13)
Homebrew/homebrew-cask (git revision 5a38c91612; last commit 2021-11-13)
```

TL;DR -- my install of `brew` isn't at `/opt/homebrew/bin/brew`

**Comment by brandon-fryslie** [comment]
Should be resolved by this commit (Jan 21, 2022)
https://github.com/brandon-fryslie/rad-plugins/commit/9f88471b3ecb068e7468ab23ec7eaff846fbe2bb

**Comment by brandon-fryslie** [comment]
Should be resolved by this commit (Jan 21, 2022)
https://github.com/brandon-fryslie/rad-plugins/commit/9f88471b3ecb068e7468ab23ec7eaff846fbe2bb
